const FETCH_HOTELDETAILS = 'FETCH_HOTELDETAILS';
const FETCH_HOTELDETAILS_SUCCESS = 'FETCH_HOTELDETAILS_SUCCESS';
const FETCH_HOTELDETAILS_FAILURE = 'FETCH_HOTELDETAILS_FAILURE';

export { FETCH_HOTELDETAILS, FETCH_HOTELDETAILS_SUCCESS, FETCH_HOTELDETAILS_FAILURE };
