const FETCH_HOTEL = 'FETCH_HOTEL';
const FETCH_HOTEL_SUCCESS = 'FETCH_HOTEL_SUCCESS';
const FETCH_HOTEL_FAILURE = 'FETCH_HOTEL_FAILURE';

export { FETCH_HOTEL, FETCH_HOTEL_SUCCESS, FETCH_HOTEL_FAILURE };
