const REGISTER_USER = 'REGISTER_USER';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export {REGISTER_USER, REGISTER_USER_SUCCESS, REGISTER_USER_FAILURE };